### ISSUE TITLE
Define more granular functions?

### ISSUE THREAD

**Issue by palermog** [benmarwick/rrtools#154]
Hi Ben,

I currently teach the article on Reproducibility Using R in my undergraduate Technical Writing for Data Science course.

To accompany their research posters, students are making GitHub repositories of their projects ready to be binderized. I'd very much like to introduce the students to the package written by the paper's lead author—this is especially true because holepunch isn't playing nicely with renv at the moment. I'd prefer not to have them wait for binder to work given install and runtime files, which is my current fallback plan.

Unfortunately, I fear it might be an overwhelming experience for them. The reason for this is that use_analysis() and use_readme_rmd() both generate a large amount of materials at once that make for a very extensive compendium. For example, the analysis function creates a bib file and a template for a journal article manuscript with a set structure. Generating a README also comes along with conduct and contributors pages, and the README itself specifies a published journal article. (And, as Issue #152 notes, the README assumes you're using that full analysis file structure.)

While I sense that these choices are because rrtools is mostly intended to provide templates for that kind of publication, I also imagine there are other use cases that wouldn't require all of these materials, writing other genres where reproducibility is a value. 

So, would it be desirable and possible to make individual functions callable for some of these compendium components? Or, alternatively, could there be arguments on the existing functions that modify them for comparably minimal compendia?

As potential alternatives, I've tried to piece together bits from other compendia-related packages, but sourcing all kinds of things is potentially overwhelming in a different way, and rrtools is currently the best option I know of for generating a DESCRIPTION and Dockerfile for use with binder.

Thanks for reading!

**Comment by benmarwick** [comment]
Hi Gregory,

Thanks for your note, yes, rrtools is narrowly focussed on compendia for a journal article. I agree there is a good case for breaking up some of the current rrtools functions into smaller single-purpose functions so the workflow can be more flexible. I will look into this, but can't promise when it might happen. I understand what you mean about the current file structure that rrtools generates potentially overwhelming students seeing it for the first time. 

For a more minimalist experience that might be much better for students, you might take a look at what @cboettig is doing at https://github.com/espm-157/reproducibility-template This will give students a GitHub repo and an instance of RStudio in the browser via codespaces (rather than Binder). Following that example, you can set up a template repo that your students can use to create their own (instead of using rrtools and its functions). For example, your template repo could have a a simple readme and folder structure that suits the needs of your students (rather than waiting for changes in rrtools). 

Hope that helps!

Ben

**Comment by palermog** [comment]
Hi Ben,

Thanks for this—I'll definitely look into using codespaces!

Greg
