### ISSUE TITLE
evaluate package containerit for use_dockerfile()

### ISSUE THREAD

**Issue by nuest** [benmarwick/rrtools#19]
Just learned about this today and hope you will evaluate `containerit` for the function `rrtools::use_dockerfile()`. More info:

- https://github.com/o2r-project/containerit/
- http://o2r.info/2017/05/30/containerit-package/

**Comment by benmarwick** [comment]
Thanks, yes, I have tried it. My experience was that it was not immediately suitable because:

- it made overly complex dockerfiles with many dependencies. Since we use rocker/verse as our base image, we don't need to install so many dependencies such as pandoc, tidyverse, etc. I didn't see how containerit could deal with that. 
- it didn't give correct paths for rendering Rmd files. There seemed to be excess slashes that shouldn't be there. I couldn't make a docker container from the dockerfiles that containerit made. 

But perhaps I had a bad experience. If you try it can you update this thread?

But when I was experimenting with it, I noticed the [sysreqs](https://sysreqs.r-hub.io/) package and service, which we could use to get the linux libraries that some R packages need.

**Comment by nuest** [comment]
Thanks @benmarwick for trying out the package, I will look into the issue hopefully soon.

On the `rocker/verse` topic: right, base images can simplify a lot, you can stay updated on that here: https://github.com/o2r-project/containerit/issues/93

**Comment by nuest** [comment]
Just wondering: with the filtering of existing packages based on the base image, would you re-consider this idea?

Alternatively, `rrtools` could use `sysreqs` directly and at least suggest system dependencies a user might have to add to the Dockerfile.

**Comment by benmarwick** [comment]
Will take another and continue this issue at #107
