### ISSUE TITLE
ERROR: installing package DESCRIPTION failed for package 'rrtools'

### ISSUE THREAD

**Issue by guhjy** [benmarwick/rrtools#42]
> devtools::install_github("benmarwick/rrtools")
Downloading GitHub repo benmarwick/rrtools@master
from URL https://api.github.com/repos/benmarwick/rrtools/zipball/master
Installing rrtools
"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Jinn-Yuh/AppData/Local/Temp/RtmpwZgVAC/devtools2fb0eca7ba1/benmarwick-rrtools-45c4a9b"  \
  --library="D:/Dropbox/Stat/R/Library" --install-tests 

* installing *source* package 'rrtools' ...
Error in parse(con, encoding = "UTF-8") : 
invalid multibyte character in parser at line 4
ERROR: installing package DESCRIPTION failed for package 'rrtools'
* removing 'D:/Dropbox/Stat/R/Library/rrtools'
Installation failed: Command failed (1)

**Comment by nevrome** [comment]
Could be a localization problem. Can you please post the output of
```
sessionInfo()
```

**Comment by guhjy** [comment]
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Traditional)_Taiwan.950 
[2] LC_CTYPE=Chinese (Traditional)_Taiwan.950   
[3] LC_MONETARY=Chinese (Traditional)_Taiwan.950
[4] LC_NUMERIC=C                                
[5] LC_TIME=Chinese (Traditional)_Taiwan.950    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.2  R6_2.2.2       
 [4] tools_3.4.2     withr_2.0.0     curl_3.0       
 [7] yaml_2.1.14     memoise_1.1.0   git2r_0.19.0   
[10] digest_0.6.12   devtools_1.13.3

**Comment by nevrome** [comment]
Localization problems are always hard to debug and as I have no Windows system with East Asian language support I can't test anything. Maybe you could try to [change your localization to english](https://stackoverflow.com/a/26674852/3216883). 
To dive deeper into this rabbit hole: `?Sys.getlocale`

Do you only have this problem with rrtools or also with other packages you install from github?

**Comment by guhjy** [comment]
No, I have no problems installing other packages from github.

**Comment by benmarwick** [comment]
Yes, this is tricky because of the difficulty in reproducing the problem. I bet it's the ü and ß in Nils' name that is the cause of this error. One solution could be 

```
Sys.setlocale("LC_ALL","English")
```
Or other ideas at https://stackoverflow.com/questions/16347731/how-to-change-the-locale-of-r-in-rstudio

Another option is for @guhjy to fork this repo, get rid of the ü and ß in the DESCRIPTION, and try to install that. Or we could make a branch like that.

**Comment by guhjy** [comment]
I fork this repo, get rid of the ü and ß in the DESCRIPTION and it works. Thank you for your help.

**Comment by benmarwick** [comment]
Ok, thanks for trying that and reporting back. Good to know where the problem lies. 

Can we ask @nmueller18 if he is ok for us to use a simplified version of his name that uses u instead ü and ss instead of ß in the DESCRIPTION? 

That change will make this pkg more accessible to R users with Chinese locales, like @guhjy, and perhaps other non-western locales.

**Comment by nmueller18** [comment]
Of cause it is okay. In fact, I do this myself when writing e-mails.

**Comment by benmarwick** [comment]
Thanks @nmueller18. @guhjy you should be able to install this from the master branch here now. Let us know if you have any problems.
