### ISSUE TITLE
allegedly missing documentation entries: use_analysis

### ISSUE THREAD

**Issue by nevrome** [benmarwick/rrtools#53]
We get [this weird warning](https://travis-ci.org/benmarwick/rrtools/builds/324749598#L1280) in the R package check. 

```
Status: 1 WARNING
checking for missing documentation entries ... WARNING
Undocumented code objects:
  ‘use_analysis’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```
`use_analysis()` [is of course](https://github.com/benmarwick/rrtools/blob/master/man/use_analysis.Rd) documented. There's a [stackoverflow thread](https://stackoverflow.com/questions/24434438/r-package-build-undocumented-code-objects) that discusses a similar problem. Maybe this could be fixed by changing the function name, but I hope for a more elegant solution. 

@benmarwick I'm pretty sure that we already discussed about this some months ago. But maybe it's good to have an open bug report to keep this in mind. It's not an important issue, but mildly unsatisfying.

**Comment by benmarwick** [comment]
Looks like we're getting this error because we have `analysis` in `.Rbuildignore`. I think that's causing it to match any file with 'analysis' in the name, and exclude those files from the build, which is where the warning is coming from. 

Following the instructions [here](https://stackoverflow.com/questions/13182634/rbuildignore-and-excluding-directories) I've changed it to `^analysis/` to specify that we only want to exclude the directory named `analysis`.
